### ISSUE TITLE
Not able to run. 

### ISSUE THREAD

**Issue by gurnoor1990** [cytoscape/cytoscape.js-tutorial-demo#6]
I have no experience with java script, however, I cloned the repo and tried to run it locally. Styling is the same, however no network is available on the browser window. Do I need any other dependency.

**Comment by riasc** [comment]
same here...

**Comment by pumbaa666** [comment]
same here :/

**Comment by pumbaa666** [comment]
![image](https://user-images.githubusercontent.com/34394718/130436315-e8a3fc90-9b88-4f24-81b9-2b448480f8fc.png)

**Comment by maxkfranz** [comment]
The page, as hosted on GitHub pages, works.  In any case, this example is out of date.  Refer to https://blog.js.cytoscape.org/tutorials/
